### ISSUE TITLE
git add -p

### ISSUE THREAD

**Issue by felipesanches** [fabriciofx/gitflowchart#1]
No "common workflow", git add . é meio perigoso pois adiciona tudo indiscriminadamente. A minha recomendação de boa prática é usar git add -p pois isso permite ao usuário confirmar interativamente cada pedacinho de alteração que deseja conscientemente adicionar à staging area.

**Comment by fabriciofx** [comment]
@felipesanches sua ideia é interessante e faz sentido, mas depois de muito ponderar, ainda vou preferir fazer um `git add .`, pois a ideia é ficar *simples* e *fácil*, pois os fluxogramas são mais voltados pelo público leigo que, acredito eu, vai achar confuso ter que adicionar cada pedacinho. Mas obrigado pela sua sugestão! ✌️
